# Generated by Django 6.0 on 2025-12-06 15:46

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(max_length=12, unique=True)),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=500)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='joueurs', to='competitions.club')),
            ],
            options={
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
                'ordering': ['-points', 'nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('min_points', models.PositiveIntegerField(default=0)),
                ('max_points', models.PositiveIntegerField(default=4000)),
                ('is_double', models.BooleanField(default=False)),
                ('mixte', models.BooleanField(default=False)),
                ('capacite', models.PositiveIntegerField(default=64)),
            ],
            options={
                'verbose_name': 'Tableau',
                'verbose_name_plural': 'Tableaux',
                'ordering': ['date', 'libelle'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacite__gte', 0)), name='tableau_capacite_positive'), models.CheckConstraint(condition=models.Q(('min_points__gte', 0), ('max_points__lte', 4000), ('min_points__lte', models.F('max_points'))), name='tableau_bornes_points_coherentes')],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CHECKED_IN', 'Pointée'), ('WITHDRAWN', 'Forfait')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='competitions.joueur')),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_partenaire', to='competitions.joueur')),
                ('tableau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='competitions.tableau')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='joueur',
            index=models.Index(fields=['licence'], name='competition_licence_23a4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='joueur',
            index=models.Index(fields=['points'], name='competition_points_04dda8_idx'),
        ),
        migrations.AddConstraint(
            model_name='joueur',
            constraint=models.CheckConstraint(condition=models.Q(('points__gte', 500)), name='joueur_points_min_500'),
        ),
        migrations.AddConstraint(
            model_name='joueur',
            constraint=models.CheckConstraint(condition=models.Q(('date_naissance__isnull', True), ('date_naissance__gte', datetime.date(1920, 1, 1)), _connector='OR'), name='joueur_dna_valide_si_renseignee'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('joueur', 'tableau')},
        ),
    ]
