# Generated by Django 6.0 on 2025-12-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='min_points',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
